### ISSUE TITLE
MLGT: Delete outdated Danish data

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/TMG#13]
From @ReesePlews 

> there are some other records that need to be deleted. in the danish section, i think you had mentioned it to me before, we should probably remove them.

We have to delete the outdated Danish data, probably from the Excel file first.

**Comment by ronaldtse** [comment]
Only these two are remaining now:

```
[tc211-termbase] term (lang: dan, ID: 226) is missing a corresponding English term, probably needs updating.
[tc211-termbase] term (lang: dan, ID: 227) is missing a corresponding English term, probably needs updating.
```

Both these terms don't exist in the English sheet of the 20190809 Edition.

**Comment by ReesePlews** [comment]
@ronaldtse i am quite sure the follow revisions in the Danish sheet can be made without incident:

226 -> 614
227 -> 859

if you can easily change in the processed file please do so. but i will upload a revised spreadsheet but will keep the same name.

**Comment by ronaldtse** [comment]
@ReesePlews let's wait for your updated file and these issues will go away. Thanks!
