### ISSUE TITLE
MLGT-Swedish: remove untranslated English terms for loading into Geolexica

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/TMG#17]
The full list is provided in the Excel file attached.

Here's a preview:
<img width="1213" alt="Screen Shot 2019-08-14 at 2 55 42 PM" src="https://user-images.githubusercontent.com/11865/63002263-16ee2600-bea8-11e9-8642-3cc668c0c8df.png">

[20190814-mlgt-swe-missing.xlsx.zip](https://github.com/ISO-TC211/TMG/files/3500171/20190814-mlgt-swe-missing.xlsx.zip)

From the discussion between @ReesePlews and the previous convener, the rows with missing translations should be removed from the MLGT.

**Comment by ReesePlews** [comment]
@ronaldtse i have changed the title. it is not an issue these terms were not translated. some MBs have not had the resources to do complete translations and that is perfectly ok. the idea here was that we did not want to show these English only records in each translated language section, in Geolexica, so they will be removed from the respective spreadsheets.

**Comment by ReesePlews** [comment]
removed

**Comment by ronaldtse** [comment]
Thanks @ReesePlews!!
