### ISSUE TITLE
French metadata contact information update

### ISSUE THREAD

**Issue by ReesePlews** [ISO-TC211/TMG#20]
2019-10-15 via email; updates to the contact people for France. 
will need to get their email address to confirm as informed via 3rd party.

**Comment by ReesePlews** [comment]
new contacts already members of TMG;
updated; pending MLGT publication

**Comment by ronaldtse** [comment]
Thanks @ReesePlews !

**Comment by ronaldtse** [comment]
Fixed in MLGT 2019-10-26, closed.
