### ISSUE TITLE
Some reference sources not immediately usable

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/TMG#3]
@ReesePlews apparently some of the reference sources are not in an immediately usable form. Can we get these fixed in the MLGT Excel? Thanks!

* "ISO 10303‑227:2005" has a not standard hyphen
* "ISO 19108;2002" has semicolon instead colon

From https://github.com/riboseinc/tc211-termbase/issues/7

**Comment by ReesePlews** [comment]
@ronaldtse thank you Ron,  i will fix these when i release the update later this month. please keep this open until it is corrected.

**Comment by ronaldtse** [comment]
Thanks @ReesePlews ! Once it is done please help close this ticket then!
